# ??????
server:
  port: 8090

# ????
blog:
  # ????
  name: Naccl's Blog
  # ????????????ip???
  # ????URL https://api.naccl.top/blog
  api: http://localhost:${server.port}
  # ????URL https://admin.naccl.top
  cms: http://localhost:8080
  # ????URL https://naccl.top
  view: http://localhost:8081

# ???????
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cw_blog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: this201314

  # Redis????
  redis:
    host: localhost
    #password: this201314
    port: 6379
    database: 0
    timeout: 10000ms

  # ???? - ?????,?????????????"spring mail ???"
  mail:
    host: smtp.mxhichina.com
    port: 465
    username: admin@example.com
    password: 123456
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
          ssl:
            enable: true

# MyBatis??
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# ??????
logging:
  level:
    root: info
    top.naccl: debug
  file:
    name: blog-api/log/blog-dev

# Token??
token:
  # 1000 * 60 * 60 * 24 * 3 token????
  expireTime: 259200000
  # ???????????,??????token???
  secretKey: abcdefghijklmnopqrstuvwxyz

# ????
comment:
  notify:
    # ??????????: Telegram=tg ??=mail (?????????????)
    channel: mail
  # ?????????
  default-open: true

# Telegram Bot??
# ??????????,????????
tg:
  bot:
    api: https://api.telegram.org/bot
    # bot?token,??? @BotFather ???
    token: 1234567890:qwertyuiopasdfghjklzxcvbnm
    # ?????bot?????id
    chat-id: 1234567890
    # ??????
    use-proxy: false
    # ????????
    use-reverse-proxy: true
    # ????URL,?????,??API??????
    reverse-proxy-url: https://tg-api-open.naccl.workers.dev

# ????,???????? (??????Telegram??)
http:
  proxy:
    server:
      host: 127.0.0.1
      port: 7890
      timeout: 10000

# ????
upload:
  # ???QQ??????: ??:local GitHub:github ???:upyun
  channel: local

  # ????????
  file:
    # ?????????? Windows????: C:/Users/nblog/Desktop/upload/ Linux????:/home/nblog/upload/
    path: /Users/naccl/Desktop/upload/
    access-path: /image/**
    resources-locations: file:${upload.file.path}

  # GitHub?? - ??????????,????????
  github:
    # GitHub token ??? https://naccl.github.io/PictureHosting/#/pictureHosting/help
    token: ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    username: Naccl
    # ???????GitHub???
    repos: test
    # ?????????? ????"/" ????"/"
    repos-path: /comment/avatar

  # ????? - ????? https://help.upyun.com/knowledge-base/quick_start/
  upyun:
    # ??????
    bucket-name: nblog
    # ?????
    username: naccl
    # ?????
    password: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
    # ????
    path: /comment/avatar
    # CDN????
    domain: https://cdn.example.com